const typography = require('@tailwindcss/typography');

function withOpacity(variableName) {
	return ({ opacityValue }) => {
		if (opacityValue !== undefined) {
			return `rgba(var(${variableName}), ${opacityValue})`;
		}
		return `rgba(var(${variableName}))`;
	};
}

module.exports = {
	darkMode: 'class',
	content: ['./hugo_stats.json'],
	plugins: [typography],
	theme: {
		extend: {
			fontFamily: {
				serif: ['Noto Serif', 'serif'],
				sans: ['Noto Sans', 'sans-serif'],
				mono: ['monospace'],
			},

			textColor: {
				skin: {
					'light-grey1': withOpacity('--light-grey1'),
					'light-grey2': withOpacity('--light-grey2'),
					'light-grey3': withOpacity('--light-grey3'),
					'light-grey4': withOpacity('--light-grey4'),
					'light-grey5': withOpacity('--light-grey5'),
					'light-grey6': withOpacity('--light-grey6'),
					'light-grey7': withOpacity('--light-grey7'),
					'light-grey8': withOpacity('--light-grey8'),
					'light-grey9': withOpacity('--light-grey9'),
					'light-grey10': withOpacity('--light-grey10'),
					'light-grey11': withOpacity('--light-grey11'),
					'light-grey12': withOpacity('--light-grey12'),

					'dark-grey1': withOpacity('--dark-grey1'),
					'dark-grey2': withOpacity('--dark-grey2'),
					'dark-grey3': withOpacity('--dark-grey3'),
					'dark-grey4': withOpacity('--dark-grey4'),
					'dark-grey5': withOpacity('--dark-grey5'),
					'dark-grey6': withOpacity('--dark-grey6'),
					'dark-grey7': withOpacity('--dark-grey7'),
					'dark-grey8': withOpacity('--dark-grey8'),
					'dark-grey9': withOpacity('--dark-grey9'),
					'dark-grey10': withOpacity('--dark-grey10'),
					'dark-grey11': withOpacity('--dark-grey11'),
					'dark-grey12': withOpacity('--dark-grey12'),

					'light-brand1': withOpacity('--light-brand1'),
					'light-brand2': withOpacity('--light-brand2'),
					'light-brand3': withOpacity('--light-brand3'),
					'light-brand4': withOpacity('--light-brand4'),
					'light-brand5': withOpacity('--light-brand5'),
					'light-brand6': withOpacity('--light-brand6'),
					'light-brand7': withOpacity('--light-brand7'),
					'light-brand8': withOpacity('--light-brand8'),
					'light-brand9': withOpacity('--light-brand9'),
					'light-brand10': withOpacity('--light-brand10'),
					'light-brand11': withOpacity('--light-brand11'),
					'light-brand12': withOpacity('--light-brand12'),

					'dark-brand1': withOpacity('--dark-brand1'),
					'dark-brand2': withOpacity('--dark-brand2'),
					'dark-brand3': withOpacity('--dark-brand3'),
					'dark-brand4': withOpacity('--dark-brand4'),
					'dark-brand5': withOpacity('--dark-brand5'),
					'dark-brand6': withOpacity('--dark-brand6'),
					'dark-brand7': withOpacity('--dark-brand7'),
					'dark-brand8': withOpacity('--dark-brand8'),
					'dark-brand9': withOpacity('--dark-brand9'),
					'dark-brand10': withOpacity('--dark-brand10'),
					'dark-brand11': withOpacity('--dark-brand11'),
					'dark-brand12': withOpacity('--dark-brand12'),

					'light-cta1': withOpacity('--light-cta1'),
					'light-cta2': withOpacity('--light-cta2'),
					'light-cta3': withOpacity('--light-cta3'),
					'light-cta4': withOpacity('--light-cta4'),
					'light-cta5': withOpacity('--light-cta5'),
					'light-cta6': withOpacity('--light-cta6'),
					'light-cta7': withOpacity('--light-cta7'),
					'light-cta8': withOpacity('--light-cta8'),
					'light-cta9': withOpacity('--light-cta9'),
					'light-cta10': withOpacity('--light-cta10'),
					'light-cta11': withOpacity('--light-cta11'),
					'light-cta12': withOpacity('--light-cta12'),

					'dark-cta1': withOpacity('--dark-cta1'),
					'dark-cta2': withOpacity('--dark-cta2'),
					'dark-cta3': withOpacity('--dark-cta3'),
					'dark-cta4': withOpacity('--dark-cta4'),
					'dark-cta5': withOpacity('--dark-cta5'),
					'dark-cta6': withOpacity('--dark-cta6'),
					'dark-cta7': withOpacity('--dark-cta7'),
					'dark-cta8': withOpacity('--dark-cta8'),
					'dark-cta9': withOpacity('--dark-cta9'),
					'dark-cta10': withOpacity('--dark-cta10'),
					'dark-cta11': withOpacity('--dark-cta11'),
					'dark-cta12': withOpacity('--dark-cta12'),
				},
			},
			borderColor: {
				skin: {
					'light-grey1': withOpacity('--light-grey1'),
					'light-grey2': withOpacity('--light-grey2'),
					'light-grey3': withOpacity('--light-grey3'),
					'light-grey4': withOpacity('--light-grey4'),
					'light-grey5': withOpacity('--light-grey5'),
					'light-grey6': withOpacity('--light-grey6'),
					'light-grey7': withOpacity('--light-grey7'),
					'light-grey8': withOpacity('--light-grey8'),
					'light-grey9': withOpacity('--light-grey9'),
					'light-grey10': withOpacity('--light-grey10'),
					'light-grey11': withOpacity('--light-grey11'),
					'light-grey12': withOpacity('--light-grey12'),

					'dark-grey1': withOpacity('--dark-grey1'),
					'dark-grey2': withOpacity('--dark-grey2'),
					'dark-grey3': withOpacity('--dark-grey3'),
					'dark-grey4': withOpacity('--dark-grey4'),
					'dark-grey5': withOpacity('--dark-grey5'),
					'dark-grey6': withOpacity('--dark-grey6'),
					'dark-grey7': withOpacity('--dark-grey7'),
					'dark-grey8': withOpacity('--dark-grey8'),
					'dark-grey9': withOpacity('--dark-grey9'),
					'dark-grey10': withOpacity('--dark-grey10'),
					'dark-grey11': withOpacity('--dark-grey11'),
					'dark-grey12': withOpacity('--dark-grey12'),

					'light-brand1': withOpacity('--light-brand1'),
					'light-brand2': withOpacity('--light-brand2'),
					'light-brand3': withOpacity('--light-brand3'),
					'light-brand4': withOpacity('--light-brand4'),
					'light-brand5': withOpacity('--light-brand5'),
					'light-brand6': withOpacity('--light-brand6'),
					'light-brand7': withOpacity('--light-brand7'),
					'light-brand8': withOpacity('--light-brand8'),
					'light-brand9': withOpacity('--light-brand9'),
					'light-brand10': withOpacity('--light-brand10'),
					'light-brand11': withOpacity('--light-brand11'),
					'light-brand12': withOpacity('--light-brand12'),

					'dark-brand1': withOpacity('--dark-brand1'),
					'dark-brand2': withOpacity('--dark-brand2'),
					'dark-brand3': withOpacity('--dark-brand3'),
					'dark-brand4': withOpacity('--dark-brand4'),
					'dark-brand5': withOpacity('--dark-brand5'),
					'dark-brand6': withOpacity('--dark-brand6'),
					'dark-brand7': withOpacity('--dark-brand7'),
					'dark-brand8': withOpacity('--dark-brand8'),
					'dark-brand9': withOpacity('--dark-brand9'),
					'dark-brand10': withOpacity('--dark-brand10'),
					'dark-brand11': withOpacity('--dark-brand11'),
					'dark-brand12': withOpacity('--dark-brand12'),

					'light-cta1': withOpacity('--light-cta1'),
					'light-cta2': withOpacity('--light-cta2'),
					'light-cta3': withOpacity('--light-cta3'),
					'light-cta4': withOpacity('--light-cta4'),
					'light-cta5': withOpacity('--light-cta5'),
					'light-cta6': withOpacity('--light-cta6'),
					'light-cta7': withOpacity('--light-cta7'),
					'light-cta8': withOpacity('--light-cta8'),
					'light-cta9': withOpacity('--light-cta9'),
					'light-cta10': withOpacity('--light-cta10'),
					'light-cta11': withOpacity('--light-cta11'),
					'light-cta12': withOpacity('--light-cta12'),

					'dark-cta1': withOpacity('--dark-cta1'),
					'dark-cta2': withOpacity('--dark-cta2'),
					'dark-cta3': withOpacity('--dark-cta3'),
					'dark-cta4': withOpacity('--dark-cta4'),
					'dark-cta5': withOpacity('--dark-cta5'),
					'dark-cta6': withOpacity('--dark-cta6'),
					'dark-cta7': withOpacity('--dark-cta7'),
					'dark-cta8': withOpacity('--dark-cta8'),
					'dark-cta9': withOpacity('--dark-cta9'),
					'dark-cta10': withOpacity('--dark-cta10'),
					'dark-cta11': withOpacity('--dark-cta11'),
					'dark-cta12': withOpacity('--dark-cta12'),
				},
			},
			backgroundColor: {
				skin: {
					'light-grey1': withOpacity('--light-grey1'),
					'light-grey2': withOpacity('--light-grey2'),
					'light-grey3': withOpacity('--light-grey3'),
					'light-grey4': withOpacity('--light-grey4'),
					'light-grey5': withOpacity('--light-grey5'),
					'light-grey6': withOpacity('--light-grey6'),
					'light-grey7': withOpacity('--light-grey7'),
					'light-grey8': withOpacity('--light-grey8'),
					'light-grey9': withOpacity('--light-grey9'),
					'light-grey10': withOpacity('--light-grey10'),
					'light-grey11': withOpacity('--light-grey11'),
					'light-grey12': withOpacity('--light-grey12'),

					'dark-grey1': withOpacity('--dark-grey1'),
					'dark-grey2': withOpacity('--dark-grey2'),
					'dark-grey3': withOpacity('--dark-grey3'),
					'dark-grey4': withOpacity('--dark-grey4'),
					'dark-grey5': withOpacity('--dark-grey5'),
					'dark-grey6': withOpacity('--dark-grey6'),
					'dark-grey7': withOpacity('--dark-grey7'),
					'dark-grey8': withOpacity('--dark-grey8'),
					'dark-grey9': withOpacity('--dark-grey9'),
					'dark-grey10': withOpacity('--dark-grey10'),
					'dark-grey11': withOpacity('--dark-grey11'),
					'dark-grey12': withOpacity('--dark-grey12'),

					'light-brand1': withOpacity('--light-brand1'),
					'light-brand2': withOpacity('--light-brand2'),
					'light-brand3': withOpacity('--light-brand3'),
					'light-brand4': withOpacity('--light-brand4'),
					'light-brand5': withOpacity('--light-brand5'),
					'light-brand6': withOpacity('--light-brand6'),
					'light-brand7': withOpacity('--light-brand7'),
					'light-brand8': withOpacity('--light-brand8'),
					'light-brand9': withOpacity('--light-brand9'),
					'light-brand10': withOpacity('--light-brand10'),
					'light-brand11': withOpacity('--light-brand11'),
					'light-brand12': withOpacity('--light-brand12'),

					'dark-brand1': withOpacity('--dark-brand1'),
					'dark-brand2': withOpacity('--dark-brand2'),
					'dark-brand3': withOpacity('--dark-brand3'),
					'dark-brand4': withOpacity('--dark-brand4'),
					'dark-brand5': withOpacity('--dark-brand5'),
					'dark-brand6': withOpacity('--dark-brand6'),
					'dark-brand7': withOpacity('--dark-brand7'),
					'dark-brand8': withOpacity('--dark-brand8'),
					'dark-brand9': withOpacity('--dark-brand9'),
					'dark-brand10': withOpacity('--dark-brand10'),
					'dark-brand11': withOpacity('--dark-brand11'),
					'dark-brand12': withOpacity('--dark-brand12'),

					'light-cta1': withOpacity('--light-cta1'),
					'light-cta2': withOpacity('--light-cta2'),
					'light-cta3': withOpacity('--light-cta3'),
					'light-cta4': withOpacity('--light-cta4'),
					'light-cta5': withOpacity('--light-cta5'),
					'light-cta6': withOpacity('--light-cta6'),
					'light-cta7': withOpacity('--light-cta7'),
					'light-cta8': withOpacity('--light-cta8'),
					'light-cta9': withOpacity('--light-cta9'),
					'light-cta10': withOpacity('--light-cta10'),
					'light-cta11': withOpacity('--light-cta11'),
					'light-cta12': withOpacity('--light-cta12'),

					'dark-cta1': withOpacity('--dark-cta1'),
					'dark-cta2': withOpacity('--dark-cta2'),
					'dark-cta3': withOpacity('--dark-cta3'),
					'dark-cta4': withOpacity('--dark-cta4'),
					'dark-cta5': withOpacity('--dark-cta5'),
					'dark-cta6': withOpacity('--dark-cta6'),
					'dark-cta7': withOpacity('--dark-cta7'),
					'dark-cta8': withOpacity('--dark-cta8'),
					'dark-cta9': withOpacity('--dark-cta9'),
					'dark-cta10': withOpacity('--dark-cta10'),
					'dark-cta11': withOpacity('--dark-cta11'),
					'dark-cta12': withOpacity('--dark-cta12'),
				},
			},

			typography: (theme) => ({}),
		},
	},
};
